### ISSUE TITLE
[support] socks5 or http username and password authentication

### ISSUE THREAD

**Issue by passwa11** [mmpx12/proxy-check#3]
if local proxy file include authentication of socks5 or http:
```
http://admin:pass@1.1.1.1:10008
socks5://admin:pass@2.2.2.2:1080
```

**Comment by mmpx12** [comment]
@passwa11 no time this w-e, but i ll add this next week

**Comment by passwa11** [comment]
@mmpx12 thx dude. Looking forward to your update.

**Comment by mmpx12** [comment]
@passwa11 I tested and its already working: 

```sh
 $ cat in.txt 
socks5://user4:passwd4@nl-vps:9999
http://1.1.1.1:80
http://user4:passwd4@nl-vps:5599
http://2.2.2.2:80

$ proxy-check  -r -t 1  in.txt

Valid proxies:

socks5://user4:passwd4@nl-vps:9999
http://user4:passwd4@nl-vps:5599
```

If its not working for you please provide proxies file proxy-check version.

**Comment by passwa11** [comment]
thks your reply.i will give u the some socks link some times
