### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by SugarRainbow** [mmpx12/proxy-check#4]
v1.1.1 windows 386&amd64 not worked on Windows 10.
When they open a command menu flashes up, then nothing.

**Comment by mmpx12** [comment]
How did you run the program? Double click on it inside file manage or `./proxy-check` inside a powershell or cmd window?

**Comment by SugarRainbow** [comment]
Double click on it inside file manage

**Comment by SugarRainbow** [comment]
Sorry, I found the problem, I should use it in powershell
